<?php
$pageTitle = "Kartu Stok | PBD Project";
include "../header.php";

$result = $conn->query("SELECT * FROM v_kartu_stok ORDER BY idkartu_stok DESC");
?>

<div class="d-flex justify-content-between align-items-center mb-3">
    <h3 class="text-gradient fw-bold"><i class="bi bi-card-list"></i> Kartu Stok Barang</h3>
    <span class="badge bg-secondary">Auto Generated by Trigger</span>
</div>

<div class="table-responsive">
<table class="table table-hover table-bordered align-middle text-center shadow-sm bg-white">
    <thead class="table-primary">
        <tr>
            <th>ID</th>
            <th>Nama Barang</th>
            <th>Jenis Transaksi</th>
            <th>Masuk</th>
            <th>Keluar</th>
            <th>Sisa Stok</th>
            <th>Tanggal</th>
        </tr>
    </thead>
    <tbody>
    <?php while($r = $result->fetch_assoc()): ?>
        <tr>
            <td><?= $r['idkartu_stok'] ?></td>
            <td><?= $r['nama_barang'] ?></td>
            <td><?= $r['jenis_transaksi'] == 'M' ? 'Masuk' : 'Keluar' ?></td>
            <td><?= $r['masuk'] ?></td>
            <td><?= $r['keluar'] ?></td>
            <td><?= $r['sisa_stok'] ?></td>
            <td><?= $r['created_at'] ?></td>
        </tr>
    <?php endwhile; ?>
    </tbody>
</table>
</div>

<?php include "../footer.php"; ?>
